logs:
  1: log-reports.yml
  2: another-log.yml
  3: custom-log.yml
messages:
  no-permission: "&cУ вас нет прав."
  usage: "&cИспользование: /logtext [номер] [текст]"
  unknown-log: "&cФайл с таким номером не настроен."
  success: "&aЗапись добавлена."
  error: "&cНе удалось записать сообщение в файл."
  reload: "&aКонфигурация LogWriter перезагружена."
