logs:
  "1": "../PlayerReport/log.yml"
  "2": "../Punishment/log.yml"
  "3": "../AnotherPlugin/log.yml"
  "4": "../SomePlugin/log.yml"
  "5": "../TestPlugin/log.yml"
messages:
  no-permission: "&cУ вас нет прав."
  usage: "&cИспользование: /logtext [номер] [текст]"
  unknown-log: "&cФайл с таким номером не настроен."
  success: "&aЗапись добавлена."
  error: "&cНе удалось записать сообщение в файл."
  reload: "&aКонфигурация LogWriter перезагружена."
